language: cpp
compiler: gcc
language: cpp
sudo: required
dist: trusty
os: linux

branches:
  only:
    - develop
    - master
    - refactor/unittest 

before_install:
    - echo Install dependencies
    - travis-ci/deps.sh

install:
    - echo Building INDI Core
    - travis-ci/build-core.sh 
    - travis-ci/build-3rdparty.sh
    - travis-ci/build-deb-packages.sh

script:
    - pwd
    - cd libindi/test
    - ctest -V

